### ISSUE TITLE
[5.0.7] Battle Pet level up alert still firing randomly

### ISSUE THREAD

**Issue by SoulCookie** [donniedice/BLU#22]
Continuation/reopening of #20 -- I'm still getting the battle pet level up sound on random events with BLU 5.0.7. (Sorry.)

And just for the record, I have confirmed that the sound I'm hearing is **only** assigned to the battle pet event.

**Comment by donniedice** [comment]
Will check it after work tonight. Im currently building out an entire level tracking system for pets to solve this issue once and for all.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by donniedice** [comment]
I'm going to keep this open until I nail it down. Blizzard api only fires bettle_pet_level event in actually pet battles... so that's where the issue was... and there is no straight-forward way to track in-real-time current pet levels without some hacky stuff.

At this point I've basically built an entire second addon for the battle-pet tracking stuff.

**Comment by donniedice** [comment]
This is Fixed. Finally.
